### ISSUE TITLE
1702 not avaiable

### ISSUE THREAD

**Issue by RetroTinkering** [codedchip/AMSGateArray#1]
Hi,

Can the MCP1703T-3602E/CB variant be used? Seems from the data sheat to have same specs but with a higher upper tolerance ... these are available widely.

**Comment by codedchip** [comment]
Hi,

If you mean this:

https://www.mouser.co.uk/ProductDetail/Microchip-Technology/MCP1703T-3602E-CB?qs=6qKXPk0vzx2Tb143pHGiJQ%3D%3D

Then yes, almost certainly. I've never tried it but I see no reason why not.

Thanks

**Comment by RetroTinkering** [comment]
Thank you, that's the one, excellent work BTW will be making a dozen  or so of these up and will ask user to provide feedback straight here.

**Comment by codedchip** [comment]
That's fantastic. Thanks.
