### ISSUE TITLE
Prgramming issue

### ISSUE THREAD

**Issue by RetroTinkering** [codedchip/AMSGateArray#2]
Sorry wish I couuld ask this elsewhere  but cannot find another way to contact you.

I have made uup a few of these boards but am stumped on how  to program the .jed files, do the boards need to  be programmed  in place on a CPC board to power the 95288, what software and hardware are you using to program them?

Once again apologise but my only experience of programming CPLD is with them on a board where they are programmed  from a Raspberry Pi.

**Comment by codedchip** [comment]
My email address is in all the source files. Feel free to send me a mail.

**Comment by RetroTinkering** [comment]
Thanks again, problem was two things  the Xilinx drivers  on  Windows 10, which is a bit of a mess to sort ouut and  the jig I made to supply voltage to the amsgatearray was supplying an  incorrect voltage which was way to low, test the  ones I made uup and  they are working, so all good. .. thanks agaimn
